# new/veo3/pipeline.py
import os
import sys
import time
import json
import math
import random
import hashlib
import glob
from pathlib import Path
from typing import Dict, List, Tuple

import cv2
import numpy as np
from PIL import Image
from tqdm import tqdm

# This script automates the multi-step process for generating a synthetic dataset.
# To configure, modify the values in the `Config` class below.

# --- Add project root to sys.path to allow imports ---
sys.path.append(str(Path(__file__).resolve().parents[2]))

from yolo_utils import create_yolo_dataset_structure
from ultralytics import SAM
from libcom import image_harmonization

# ============================================================ 
# SECTION 1: CONFIGURATION
# ============================================================ 

class Config:
    """
    Configuration class for the data generation pipeline.
    Modify the paths and parameters here.
    """
    # --- Step 1 Inputs ---
    # Directory containing the initial set of images and camera_poses.json
    INPUT_DIR = Path("./input")
    NUM_VIEWS_TO_SELECT = 3

    # --- Step 2 Inputs ---
    # Path to the video file generated by your external (VEO3) process.
    # The script will automatically use this file.
    VIDEO_PATH = Path("./veo3_output/video.mp4")

    # --- Step 3 Inputs & Parameters ---
    # Directory containing background images for data generation.
    BACKGROUND_DIR = Path("./dataset/train")
    # The name of the class for your object in the YOLO dataset.
    CLASS_NAME = "my_object"
    # Number of synthetic images to generate.
    TARGET_POSITIVES = 3000
    TARGET_NEGATIVES = 2000

# ============================================================ 
# SECTION 2: UTILITY AND HELPER FUNCTIONS
# ============================================================ 

def setup_logger():
    import logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    return logging.getLogger(__name__)

logger = setup_logger()

SAM_MODEL = None # Global cache for the model

# --- Pose and View Selection Helpers ---

def load_camera_poses(path: Path) -> Dict[str, dict]:
    """Loads camera poses from a JSON file."""
    logger.info(f"Loading camera poses from {path}...")
    if not path.exists():
        logger.error(f"FATAL: Camera poses file not found at {path}")
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def compute_center(poses: Dict[str, dict]) -> List[float]:
    xs, ys, zs = [], [], []
    for p in poses.values():
        lx, ly, lz = p["look_at"]
        xs.append(lx)
        ys.append(ly)
        zs.append(lz)
    n = len(xs) if xs else 1
    return [sum(xs)/n, sum(ys)/n, sum(zs)/n]

def compute_azimuth_elevation(position: List[float], center: List[float]) -> tuple[float, float, float]:
    cx, cy, cz = center
    px, py, pz = position
    vx, vy, vz = px - cx, py - cy, pz - cz
    r = math.sqrt(vx*vx + vy*vy + vz*vz) + 1e-8
    azimuth = math.degrees(math.atan2(vx, vz))
    elevation = math.degrees(math.asin(vy / r))
    return azimuth, elevation, r

def _fixed_grid_selection(filtered: List[dict], ideal_positions: List[Tuple[float, float]]) -> List[dict]:
    chosen = []
    remaining = filtered.copy()
    for ideal_az, ideal_el in ideal_positions:
        if not remaining: break
        best = min(remaining, key=lambda v: math.sqrt((v["azimuth"] - ideal_az)**2 + (v["elevation"] - ideal_el)**2))
        chosen.append(best)
        remaining.remove(best)
    return sorted(chosen, key=lambda v: v["azimuth"])

def _robust_greedy_selection(filtered: List[dict]) -> List[dict]:
    def vec_distance(v1, v2):
        dot = sum(a * b for a, b in zip(v1["vec"], v2["vec"]))
        return math.degrees(math.acos(max(-1, min(1, dot))))
    if not filtered: return []
    first = min(filtered, key=lambda v: abs(v["azimuth"]) + abs(v["elevation"]) * 3.0)
    chosen = [first]
    remaining = [v for v in filtered if v is not first]
    if len(remaining) < 2: return chosen + remaining
    second = max(remaining, key=lambda v: vec_distance(first, v) - abs(v["elevation"]) * 2)
    chosen.append(second)
    remaining = [v for v in remaining if v is not second]
    if len(remaining) < 1: return chosen + remaining
    third = max(remaining, key=lambda v: min(vec_distance(first, v), vec_distance(second, v)) - abs(v["elevation"]) * 2)
    chosen.append(third)
    return sorted(chosen, key=lambda v: v["azimuth"])

# --- Video and Segmentation Helpers ---

def frame_from_video(video_path: Path, output_dir: Path):
    logger.info(f"Extracting unique frames from video: {video_path.name}")
    output_dir.mkdir(parents=True, exist_ok=True)
    cap = cv2.VideoCapture(str(video_path))
    seen_hashes = set()
    saved_idx = 0
    with tqdm(total=int(cap.get(cv2.CAP_PROP_FRAME_COUNT)), desc="Extracting frames") as pbar:
        while True:
            ret, frame = cap.read()
            if not ret: break
            pbar.update(1)
            frame_hash = hashlib.md5(frame.tobytes()).hexdigest()
            if frame_hash in seen_hashes: continue
            seen_hashes.add(frame_hash)
            cv2.imwrite(str(output_dir / f"frame_{saved_idx:04d}.png"), frame)
            saved_idx += 1
    cap.release()
    logger.info(f"Extracted {saved_idx} unique frames to {output_dir}")

def get_sam_model():
    global SAM_MODEL
    if SAM_MODEL is None:
        try:
            logger.info("Loading SAM model...")
            # Path is relative to the project root where this script should be run from
            SAM_MODEL = SAM("sam_l.pt") 
            logger.info("SAM model loaded.")
        except Exception as e:
            logger.error(f"FATAL: Failed to load SAM model. Ensure 'sam_l.pt' is in project root. Error: {e}")
            return None
    return SAM_MODEL

def extract_clean_object(img: np.ndarray, binary_mask: np.ndarray) -> np.ndarray:
    contours, _ = cv2.findContours(binary_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours: return None
    main_contour = max(contours, key=cv2.contourArea)
    clean_mask = np.zeros_like(binary_mask)
    cv2.drawContours(clean_mask, [main_contour], -1, 255, thickness=cv2.FILLED)
    b, g, r = cv2.split(img)
    bgra = cv2.merge([b, g, r, clean_mask])
    ys, xs = np.where(clean_mask > 0)
    if len(xs) == 0: return None
    return bgra[ys.min():ys.max(), xs.min():xs.max()]

# ============================================================ 
# SECTION 3: DATASET BUILDER (from no_veo3)
# ============================================================ 

class DatasetBuilder:
    def __init__(self, obj_root, bg_root, output_root, class_id=0, target_size=1024, tile_size=256, val_split_ratio=0.2):
        self.obj_root = obj_root
        self.bg_root = bg_root
        self.output_root = output_root
        self.class_id = class_id
        self.target_size = target_size
        self.tile_size = tile_size
        self.val_split_ratio = val_split_ratio
        
        logger.info("🚀 Loading Image Harmonization Model...")
        self.harmonization_net = image_harmonization.ImageHarmonizationModel(device=0)
        self.object_files = self._load_files(self.obj_root, ('*.png',))
        self.bg_paths = self._load_files(self.bg_root, ('*.jpg', '*.png', '*.jpeg'))
        logger.info(f"Loaded {len(self.object_files)} objects and {len(self.bg_paths)} backgrounds.")

    def _load_files(self, root_dir, extensions):
        return [p for ext in extensions for p in Path(root_dir).rglob(ext)]

    def _create_tiled_bg(self, bg_paths_chunk):
        rows = []
        for i in range(0, 16, 4):
            cols = []
            for j in range(4):
                try:
                    img = cv2.imread(str(bg_paths_chunk[i+j]))
                    img = cv2.resize(img, (self.tile_size, self.tile_size)) if img is not None else np.zeros((self.tile_size, self.tile_size, 3), np.uint8)
                except Exception:
                    img = np.zeros((self.tile_size, self.tile_size, 3), np.uint8)
                cols.append(img)
            rows.append(np.hstack(cols))
        return np.vstack(rows)

    def _get_tiled_backgrounds(self, target_count):
        if not self.bg_paths:
            raise ValueError("No background images found.")
        if len(self.bg_paths) < 16:
             raise ValueError(f"Not enough background images for even one tile! Need 16, have {len(self.bg_paths)}.")
        
        num_tiles_possible = len(self.bg_paths) // 16
        if num_tiles_possible < target_count:
            logger.warning(f"Not enough unique backgrounds to create {target_count} tiles. Will reuse backgrounds.")
            bg_chunks = [random.sample(self.bg_paths, 16) for _ in range(target_count)]
        else:
            random.shuffle(self.bg_paths)
            bg_chunks = [self.bg_paths[i:i+16] for i in range(0, target_count * 16, 16)]

        return [self._create_tiled_bg(chunk) for chunk in tqdm(bg_chunks, desc="Tiling backgrounds")]

    def _get_yolo_label(self, mask):
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if not contours: return None
        cnt = max(contours, key=cv2.contourArea)
        epsilon = 0.0001 * cv2.arcLength(cnt, True)
        approx = cv2.approxPolyDP(cnt, epsilon, True)
        if len(approx) < 3: return None
        points_str = [f"{(p[0][0]/self.target_size):.6f} {(p[0][1]/self.target_size):.6f}" for p in approx]
        return f"{self.class_id} " + " ".join(points_str)

    def _process_and_save(self, bg, split_name, filename, is_positive):
        img_path = self.output_root / 'images' / split_name / f"{filename}.jpg"
        lbl_path = self.output_root / 'labels' / split_name / f"{filename}.txt"
        if not is_positive:
            cv2.imwrite(str(img_path), bg)
            lbl_path.touch()
            return 1
        
        obj_path = random.choice(self.object_files)
        obj_img = cv2.imread(str(obj_path), cv2.IMREAD_UNCHANGED)
        if obj_img is None: return 0

        h, w = obj_img.shape[:2]
        scale = (random.uniform(0.15, 0.35) * self.target_size) / max(h, w) if max(h, w) > 0 else 1.0
        obj_img = cv2.resize(obj_img, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
        h_obj, w_obj = obj_img.shape[:2]
        if h_obj == 0 or w_obj == 0: return 0
        
        y_pos, x_pos = random.randint(0, self.target_size - h_obj), random.randint(0, self.target_size - w_obj)
        
        mask = np.zeros((self.target_size, self.target_size), dtype=np.uint8)
        
        if obj_img.shape[2] != 4:
            logger.warning(f"Object image {obj_path.name} does not have an alpha channel. Skipping.")
            return 0
        
        alpha = obj_img[:, :, 3]
        mask[y_pos:y_pos+h_obj, x_pos:x_pos+w_obj] = (alpha > 127) * 255
        
        label = self._get_yolo_label(mask)
        if not label: return 0
        
        composite = bg.copy()
        alpha_s = obj_img[:, :, 3] / 255.0
        alpha_s = np.dstack((alpha_s, alpha_s, alpha_s)) # Make it 3-channel
        
        composite_roi = composite[y_pos:y_pos+h_obj, x_pos:x_pos+w_obj]
        obj_bgr = obj_img[:, :, :3]
        
        composite_roi[:] = alpha_s * obj_bgr + (1.0 - alpha_s) * composite_roi
        
        harmonized = self.harmonization_net(cv2.cvtColor(composite, cv2.COLOR_BGR2RGB), mask)
        final_bgr = cv2.cvtColor(np.clip(harmonized * 255 if harmonized.max() <= 1.0 else harmonized, 0, 255).astype(np.uint8), cv2.COLOR_RGB2BGR)

        cv2.imwrite(str(img_path), final_bgr)
        with open(lbl_path, "w") as f: f.write(label + "\n")
        return 1

    def generate(self, num_positives, num_negatives, class_name):
        create_yolo_dataset_structure(self.output_root, [class_name])
        total_generated = 0
        
        if not self.object_files:
            logger.warning("No object files found. Skipping positive sample generation.")
            num_positives = 0
            
        if not self.bg_paths:
            logger.error("No background files found. Cannot generate any data.")
            return

        if num_positives > 0:
            try:
                pos_bgs = self._get_tiled_backgrounds(num_positives)
                split_idx = int(len(pos_bgs) * (1 - self.val_split_ratio))
                for bg, split in tqdm(zip(pos_bgs, ['train']*split_idx + ['val']*(len(pos_bgs)-split_idx)), total=len(pos_bgs), desc="Generating positive samples"):
                    total_generated += self._process_and_save(bg, split, f"positive_{total_generated:06d}", True)
            except ValueError as e:
                logger.error(f"Could not generate positive samples: {e}")

        if num_negatives > 0:
            try:
                neg_bgs = self._get_tiled_backgrounds(num_negatives)
                split_idx = int(len(neg_bgs) * (1 - self.val_split_ratio))
                for bg, split in tqdm(zip(neg_bgs, ['train']*split_idx + ['val']*(len(neg_bgs)-split_idx)), total=len(neg_bgs), desc="Generating negative samples"):
                    total_generated += self._process_and_save(bg, split, f"negative_{total_generated:06d}", False)
            except ValueError as e:
                logger.error(f"Could not generate negative samples: {e}")

        logger.info(f"✅✅✅ Generation complete! Total images created: {total_generated} ✅✅✅")


# ============================================================ 
# SECTION 4: PIPELINE STEPS
# ============================================================ 

def step_1_select_best_views(input_dir: Path, poses_file: Path, num_views: int = 3) -> List[Path]:
    logger.info("--- Step 1: Selecting Best Views ---")
    input_images = [p for p in input_dir.glob("*") if p.suffix.lower() in {'.jpg', '.png', '.jpeg'}]
    if not input_images:
        logger.error(f"No images found in {input_dir}. Aborting.")
        return []
    poses = load_camera_poses(poses_file)
    if not poses:
        logger.warning("Could not load poses. Falling back to random selection.")
        return random.sample(input_images, min(num_views, len(input_images)))
    center = compute_center(poses)
    view_infos = []
    for filename, p in poses.items():
        if not (input_dir / filename).exists(): continue
        azimuth, elevation, distance = compute_azimuth_elevation(p["position"], center)
        az_rad, el_rad = math.radians(azimuth), math.radians(elevation)
        x, y, z = math.cos(el_rad) * math.sin(az_rad), math.sin(el_rad), math.cos(el_rad) * math.cos(az_rad)
        view_infos.append({"filename": filename, "azimuth": azimuth, "elevation": elevation, "vec": (x, y, z)})
    filtered = [v for v in view_infos if abs(v["elevation"]) <= 30.0]
    if len(filtered) < num_views:
        logger.warning(f"Only {len(filtered)} views within ±30° elevation. Using all available.")
        filtered = sorted(view_infos, key=lambda v: abs(v["elevation"]))[:max(num_views, len(view_infos))]
    ideal_positions = [(0, 0), (120, 0), (-120, 0)]
    close_to_ideal_count = sum(1 for az, el in ideal_positions for v in filtered if min(abs(v["azimuth"] - az), 360 - abs(v["azimuth"] - az)) < 25 and abs(v["elevation"] - el) < 15)
    strategy = _fixed_grid_selection if close_to_ideal_count >= 2 else _robust_greedy_selection
    logger.info(f"View distribution detected. Using {strategy.__name__} strategy.")
    chosen_views = strategy(filtered, ideal_positions) if strategy == _fixed_grid_selection else strategy(filtered)
    chosen_filenames = {v["filename"] for v in chosen_views}
    selected_paths = [p for p in input_images if p.name in chosen_filenames]
    logger.info(f"Selected {len(selected_paths)} views: {[p.name for p in selected_paths]}")
    return selected_paths

def step_2_process_video(video_path: Path, output_dir: Path) -> Path:
    logger.info("--- Step 2: Processing VEO3 Video ---")
    unique_frames_dir = output_dir / "1_unique_frames"
    segmented_objects_dir = output_dir / "2_segmented_objects"
    frame_from_video(video_path, unique_frames_dir)
    step_2b_segment_frames(unique_frames_dir, segmented_objects_dir)
    logger.info("Step 2 finished.")
    return segmented_objects_dir

def step_2b_segment_frames(frames_dir: Path, segmented_output_dir: Path):
    logger.info(f"--- Step 2b: Segmenting frames from {frames_dir} ---")
    segmented_output_dir.mkdir(parents=True, exist_ok=True)
    model = get_sam_model()
    if model is None: return
    frame_paths = sorted([p for p in frames_dir.iterdir() if p.suffix.lower() in {'.jpg', '.png', '.jpeg'}])
    if not frame_paths:
        logger.warning(f"No frames found in {frames_dir} to segment.")
        return
    logger.info(f"Found {len(frame_paths)} frames. Starting batch segmentation...")
    for i in tqdm(range(0, len(frame_paths), 16), desc="Segmenting Batches"):
        batch_paths = frame_paths[i:i+16]
        try:
            results = model.predict(batch_paths, task="segment", verbose=False)
            for frame_path, result in zip(batch_paths, results):
                if result.masks is None: continue
                original_image = cv2.imread(str(frame_path))
                if original_image is None: continue
                for mask_idx, mask in enumerate(result.masks.data):
                    obj_cropped = extract_clean_object(original_image, mask.cpu().numpy().astype(np.uint8) * 255)
                    if obj_cropped is not None:
                        cv2.imwrite(str(segmented_output_dir / f"{frame_path.stem}_obj_{mask_idx}.png"), obj_cropped)
        except Exception as e:
            logger.error(f"Error on segmentation batch starting with {batch_paths[0].name}: {e}")
    logger.info(f"Segmentation complete. Masked objects saved to {segmented_output_dir}")

def step_3_generate_data(segmented_objects_dir: Path, background_dir: Path, output_dir: Path, num_positives: int, num_negatives: int, class_name: str):
    logger.info("--- Step 3: Generating Synthetic Data ---")
    builder = DatasetBuilder(
        obj_root=segmented_objects_dir, 
        bg_root=background_dir, 
        output_root=output_dir, 
        class_id=0 # Assuming single class for now
    )
    builder.generate(num_positives=num_positives, num_negatives=num_negatives, class_name=class_name)

# ============================================================ 
# SECTION 5: MAIN EXECUTION
# ============================================================ 

def main():
    """Main pipeline execution function."""
    cfg = Config()
    
    # --- Part 1 is disabled for automatic run ---
    # poses_file = cfg.INPUT_DIR / "camera_poses.json"
    # selected_paths = step_1_select_best_views(cfg.INPUT_DIR, poses_file, num_views=cfg.NUM_VIEWS_TO_SELECT)
    # if not selected_paths:
    #     logger.error("Step 1 failed. Could not select views. Aborting.")
    #     return
    # print("\n" + "="*50 + f"\n✅ Step 1 complete. Recommended images for Veo3:\n" + "\n".join(f"  - {p}" for p in selected_paths) + "\n" + "="*50 + "\n")
    
    # --- Part 2: Process the video ---
    video_path = cfg.VIDEO_PATH
    if not video_path.is_file():
        logger.error(f"Invalid video file path in Config: {video_path}")
        logger.error("Please update the VIDEO_PATH in the Config class and run again.")
        return
            
    veo_output_dir = video_path.parent
    segmented_objects_dir = step_2_process_video(video_path, veo_output_dir)
    
    # --- Part 3: Generate the final dataset ---
    dataset_output_dir = veo_output_dir / "generated_dataset"
    step_3_generate_data(segmented_objects_dir, cfg.BACKGROUND_DIR, dataset_output_dir, cfg.TARGET_POSITIVES, cfg.TARGET_NEGATIVES, cfg.CLASS_NAME)
    
    logger.info(f"🎉 Pipeline finished successfully! Dataset generated at: {dataset_output_dir} 🎉")

if __name__ == "__main__":
    main()
